version: "3.7"

services:
    api_db:
        image: postgres
        container_name: pgsql_db
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=portfolioDb
        restart: always
        volumes:
            - database-data:/var/lib/postgresql/data/

    web_app:
        build:
            context: .
            dockerfile: BrennanHunterPortfolio/Dockerfile
        restart: always
        ports: 
            - "5000:5000"

volumes:
    database-data:
